version: "3"
services:
  api:
    build: .
    tty: true
    command: >
      bash -c "yarn clean-build
      && yarn build
      && yarn start"
    ports:
      - "5000:80"
    depends_on:
      - database

  database:
    env_file:
      - .env
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
