version: '3.9'
services:
    postgres:
        image: postgres:12
        container_name: luftcare_typeorm
        command: postgres -c 'idle_in_transaction_session_timeout=10000' -c 'max_connections=200'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: luftcare
            POSTGRES_PASSWORD: secret
        volumes:
            - luftcare-local-db:/var/lib/postgresql/data

volumes:
    luftcare-local-db:
        external: true
