version: "3"
services:
  database:
    container_name: database
    env_file:
      - .env
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"

  core-api:
    build: .
    tty: true
    restart: always
    container_name: core-api
    image: core-api-image:latest
    command: >
      bash -c "yarn install && yarn build && yarn start"
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=database
      - TYPEORM_PORT=5432
      - TYPEORM_ENTITIES=dist/entities/*
      - TYPEORM_MIGRATIONS=dist/migrations/*
      - TYPEORM_SUBSCRIBERS=dist/subscribers/*
      - TYPEORM_SEEDING_SEEDS=src/seeding/seeds/*
      - TYPEORM_SEEDING_FACTORIES=src/seeding/factories/*
      - TYPEORM_DEBUG=true
      - TYPEORM_CACHE=true
      - TYPEORM_LOGGING=all
      - APOLLO_LOG_LEVEL=trace
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_DROP_SCHEMA=false

  seeder:
    tty: true
    container_name: seeder
    image: core-api-image:latest
    command: "yarn seed:run"
    depends_on:
      - core-api
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=database
      - TYPEORM_PORT=5432
      - TYPEORM_LOGGING=silent
      - TYPEORM_ENTITIES=src/entities/*
      - TYPEORM_MIGRATIONS=src/migrations/*
      - TYPEORM_SUBSCRIBERS=src/subscribers/*
      - TYPEORM_SEEDING_SEEDS=src/seeding/seeds/*
      - TYPEORM_SEEDING_FACTORIES=src/seeding/factories/*
